version: '3.7'
services:

  mysql:
     container_name: mysql_container
     restart: always
     image: mysql:5.7
     command: --lower_case_table_names=1
     environment:
       MYSQL_ROOT_PASSWORD: '123456'
     volumes:
     # Mount mysql data
       - /Volumes/MacData/docker-data/mysql-data:/var/lib/mysql
     ports:
       - "52001:3306"
     networks:
      - my-newtork

  spring-data-jpa:
    container_name: spring-data-jpa
    image: spring-data-jpa
    ports:
      - 8080:8080
    networks:
      - my-newtork
    depends_on: 
      -  mysql  
                  
networks:
  my-newtork:
  
